Document: saslpolicyd
Title: Debian saslpolicyd Manual
Author: <insert document author here>
Abstract: This manual describes what saslpolicyd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/saslpolicyd/saslpolicyd.sgml.gz

Format: postscript
Files: /usr/share/doc/saslpolicyd/saslpolicyd.ps.gz

Format: text
Files: /usr/share/doc/saslpolicyd/saslpolicyd.text.gz

Format: HTML
Index: /usr/share/doc/saslpolicyd/html/index.html
Files: /usr/share/doc/saslpolicyd/html/*.html
