#!/bin/sh

### BEGIN INIT INFO
# Provides:          saslpolicyd 
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts sasl policyd server
# Description:       starts sasl policyd server
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/sbin/sasl-policyd.pl
NAME=sasl-policyd
DESC="sasl-policyd"
PROCESS_NAME=`basename $DAEMON`

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions


case "$1" in
	start)
		log_daemon_msg "Starting $DESC" $NAME
		if start-stop-daemon --start --quiet --oknodo --pidfile /var/run/$NAME.pid --exec $DAEMON -- $DAEMON_OPTS ; then
			log_end_msg 0
		else
			log_end_msg 1
		fi
		;;

	stop)
		log_daemon_msg "Stopping $DESC" $NAME
		if start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/$NAME.pid --name $PROCESS_NAME ; then
			log_end_msg 0
		else
			log_end_msg 1
		fi
		;;

	restart|force-reload)
		stop
		sleep 5
		start
		;;

	reload)
		restart
		;;

	status)
		status_of_proc -p /var/run/$NAME.pid "$DAEMON" $NAME && exit 0 || exit $?
		;;

	*)
		log_action_msg "Usage: $NAME {start|stop|reload|restart|status}" >&2
		exit 1
		;;
esac

exit 0
